### ISSUE TITLE
No such file or directory - cache_manifest.json

### ISSUE THREAD

**Issue by am1ru1** [ttymck/fastapi-fullstack-boilerplate#4]
@ttymck looks like a a great code. However I am getting the following error on the first, wanna check if you might know the fix?
Tried googling, not much help.

```
((fastapi-fullstack-boilerplate) ) coder@MYSERVER:~/mynotes/fastapi/fastapi-fullstack-boilerplate$ uvicorn --factory app.main:create_app --reload --port=8080
INFO:     Will watch for changes in these directories: ['/home/coder/mynotes/fastapi/fastapi-fullstack-boilerplate']
INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [31471] using statreload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/coder/.local/share/virtualenvs/fastapi-fullstack-boilerplate-IipA4anG/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/coder/.local/share/virtualenvs/fastapi-fullstack-boilerplate-IipA4anG/lib/python3.8/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/coder/.local/share/virtualenvs/fastapi-fullstack-boilerplate-IipA4anG/lib/python3.8/site-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/home/coder/.local/share/virtualenvs/fastapi-fullstack-boilerplate-IipA4anG/lib/python3.8/site-packages/uvicorn/config.py", line 454, in load
    self.loaded_app = self.loaded_app()
  File "/home/coder/mynotes/fastapi/fastapi-fullstack-boilerplate/./app/main.py", line 53, in create_app
    static_digest = StaticDigest(source_dir=settings.STATIC_DIR)
  File "/home/coder/.local/share/virtualenvs/fastapi-fullstack-boilerplate-IipA4anG/lib/python3.8/site-packages/fastapi_static_digest/digest.py", line 51, in __init__
    self.manifest = self._load_manifest()
  File "/home/coder/.local/share/virtualenvs/fastapi-fullstack-boilerplate-IipA4anG/lib/python3.8/site-packages/fastapi_static_digest/digest.py", line 54, in _load_manifest
    with open(self.manifest_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/coder/mynotes/fastapi/fastapi-fullstack-boilerplate/app/static/_digest/cache_manifest.json'
```

Here are my steps:
```
pip install pipenv
pipenv shell
pipenv install --dev
uvicorn --factory app.main:create_app --reload --port=8080
```

**Comment by am1ru1** [comment]
From the settings.py, the path is correctly translated. 
`STATIC_DIR = APP_ROOT / "static"`

However there is no _digest nor the cache_manifest within the path:
[static](https://github.com/ttymck/fastapi-fullstack-boilerplate/tree/master/app/static)

Did you manually create the folder and file?

**Comment by tmkontra** [comment]
Hi @am1ru1 thanks for raising this issue. The missing digest/cache_manifest is because the [StaticDigestCompiler](https://github.com/tmkontra/fastapi-static-digest/blob/master/src/fastapi_static_digest/compiler.py) was not run.

I updated the run server command [in the README](https://github.com/tmkontra/fastapi-fullstack-boilerplate/commit/4962b9104f736f17ea4d22d6c1bb430c85179faa) to include the "reload" environment flag: 
```
FASTAPI_STATICDIGEST_RELOAD=1 uvicorn app.main:create_app --port=8080 --reload
```

Thanks!
